sudo: false
language: generic

cache:
  directories:
    - $HOME/.stack

addons:
  apt:
    packages: [libgmp-dev, libx11-dev, libxtst-dev, libxrandr-dev]

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 |
      tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-nix --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-nix --no-terminal test --haddock --no-haddock-deps
