name:         xlib-keys-hack
version:      0.2.0
synopsis:     Some my own hacks for advanced keyboard
license:      GPL-3
license-file: LICENSE
author:       Viacheslav Lotsmanov
maintainer:   Viacheslav Lotsmanov <lotsmanov89@gmail.com>
copyright:    Copyright © 2016–2023 Viacheslav Lotsmanov
category:     System, Desktop Environment
github:       unclechu/xlib-keys-hack

default-extensions:
  - ExplicitNamespaces
  - PackageImports
  - TypeOperators
  - BangPatterns
  - ViewPatterns
  - QuasiQuotes
  - LambdaCase
  - MultiWayIf

dependencies:
  - base
  - containers
  - data-default
  - data-maybe-preserve
  - dbus
  - deepseq
  - directory
  - extra
  - lens
  - linux-evdev
  - mtl
  - process
  - qm-interpolated-string
  - safe
  - stm
  - template-haskell
  - text
  - time
  - transformers
  - type-operators
  - unix
  - X11

ghc-options:
  - -Wall
  - -O2

library:
  source-dirs: src
  extra-libraries: [Xtst]

executables:

  xlib-keys-hack:
    extra-libraries: [Xtst]
    dependencies: [xlib-keys-hack]
    ghc-options: [-threaded]
    source-dirs: app/XlibKeysHack
    main: Main.hs

  xlib-keys-hack-watch-for-window-focus-events:
    ghc-options: [-threaded]
    dependencies: [xlib-keys-hack]
    source-dirs: app/WindowFocusWatcher
    main: Main.hs

tests:

  xlib-keys-hack-utils-test:
    source-dirs: test
    main: UtilsSpec.hs
    dependencies:
      - xlib-keys-hack
      - hspec
