resolver: nightly-2019-11-10 # ghc 8.8.1
system-ghc: false
packages: [.]

extra-deps:
  # my own fork with updated "time" dependency version bounds
  - git: https://github.com/unclechu/haskell-linux-evdev
    commit: f948132fdc74a3dbe622eb35b0d0cfadeaa6aae7
  - git: https://github.com/unclechu/haskell-data-maybe-preserve
    commit: 705e3e4e85661c6c3c34f43a408b111433abb27e
